### ISSUE TITLE
[Chen] Offboarding LTER

### ISSUE THREAD

**Issue by angelchen7** [lter/scicomp#11]
## Summary

Listing all the housekeeping tasks that needs to be done before I can offboard from LTER 👋 

## Starting Tasks

- [x] make decision on schedule for half-time in October (remember to add a blurb in my email signature to say when I’m available)
- [x] touch base with Thomas to understand what fully happens to emails when folks leave NCEAS 
- [x] Email Pelagic and Marine CND to explain 
- [x] Check UCPath contact info and download paychecks
- [x] Save/export any useful issues I've worked on?
- [x] Save/export any useful files from my NCEAS Google Drive
- [x] Save/export any useful files from my NCEAS Macbook
- [x] Share access with my personal email on useful Shared Drives
- [ ] Contact Thomas for Macbook shipping label
- [x] Update team bio on website (at end of Oct/position) (remember to add Julien’s most recent email back to staff page)

## Useful links

TBA

**Comment by njlyon0** [comment]
Hey @angelchen7 ! Do you still need this issue open or is it cool to close it?

**Comment by angelchen7** [comment]
Whoops, I'll close it!

**Comment by njlyon0** [comment]
Thanks!
