### ISSUE TITLE
[Sci Comp] Integrate `make_json` into Sci Comp Tutorial on User-Specific Info

### ISSUE THREAD

**Issue by njlyon0** [lter/scicomp#12]
## Summary

Several groups have used local "syncs" of cloud storage systems to store their data (e.g., Box, Dropbox, etc.). This is not necessarily a problem but it does mean that relative file paths can't be used (or at least not for data ingestion). We've stumbled upon the idea of using a JSON to store user-specific information (including absolute file path to data and/or emails for simpler `googledrive` authentication) which seems like it'd work great in this context. However, so far we're prompting folx to build those JSONs manually which opens the door to user-error (and is itself a less-reproducible step). If we could develop a function to flexibly create a JSON with the desired contents that would be a really useful tool for some groups.

## Starting Tasks

- [x] Investigate the possibility of creating a JSON from R
- [x] Develop function variant
- [x] Add function to `ltertools`' build
    - [x] Look into whether the function could be made to add the JSON to the `.gitignore` (if the `.gitignore` exists...)
- [x] Send updated `ltertools` to CRAN
    - [x] Make GitHub release for version `1.1.0`
- [x] Update SciComp JSON tutorial (see 'useful links' section)

## Useful links

- SciComp team [tutorial on using JSONs for user-specific info](https://lter.github.io/scicomp/tutorial_json.html)
- `ltertools` package GitHub repo: [lter / ltertools](https://github.com/lter/ltertools)

**Comment by njlyon0** [comment]
## Dream

Ideally, we'd like to end up with something like the following:

```
contents <- c("path_to_data" = "users/me/documents/working_group", "email" = "me@gmail.com")

write_json(x = contents, file = "user.json")
```

**Comment by njlyon0** [comment]
## Substantial Progress!

Figured out how to create a JSON with custom contents from a named vector (uses `RJSONIO::toJSON` to do the transformation). Also developed a (simple) function variant and added the intuitive error checks (and unit tests). Pushed to `ltertools` repo (in `dev/` directory) so will wait to see if GHAs complete without problem then work on integrating into package build.

Note too that it might be nice to expand the function to--if desired--add the file it creates to the `.gitignore` (if one can be found in the directory to which the JSON is exported). Would be a simple argument but less sure how simple it'd be to edit the `.gitignore` in place.

**Comment by mbjones** [comment]
@njlyon0 agree that path management is a pain. Are you familiar with the `here` package, which seems quite similar to the approach you are taking? https://here.r-lib.org/. It even comes with a great graphic from Allison Horst:

![](https://raw.githubusercontent.com/allisonhorst/stats-illustrations/master/rstats-artwork/here.png)

Also, we've written up a few thoughts on this issue of referencing data files in scripts, with EDI datasets as an example for Delta, using both `pins` and `contentid` packages to make things much more portable and reproducible. Hope its helpful:

[Reproducible Data Access](https://learning.nceas.ucsb.edu/2023-06-delta/session_08.html) module

**Comment by njlyon0** [comment]
## Added to Package Build

`make_json` has been added to the package! Including unit tests, a demo in the vignette, and to `NEWS.md`. Need to look into the `.gitignore` facet though because that would be really nice to have as a built-in feature

**Comment by njlyon0** [comment]
## New `make_json` Function Behavior

Expanded `make_json` with a new `git_ignore` argument that expects a logical. If `git_ignore == TRUE`--and a '.gitignore' file is found in the working directory--then the JSON file name defined in the `file` argument is added to the bottom of the '.gitignore'

**Comment by njlyon0** [comment]
## Submitted to CRAN

Did the pre-release checks, incremented internal documentation to version `1.1.0` and sent to CRAN. If/when successfully published with make a GitHub release & make a plan for updating our website tutorial

**Comment by njlyon0** [comment]
## Revised & Resubmitted

Got returned because of some weird mismatch between `Authors@R` field of DESCRIPTION and the computer-generated `Author` field. Cumbersome but cutting each author to one link (their personal website) seems to have fixed the issue (or at least it isn't flagged by `devtools::check_win_devel()`). Re-submitted to CRAN so hopefully it goes through this time!

**Comment by njlyon0** [comment]
## Accepted by CRAN!

After the tweaks identified above, CRAN accepted `1.1.0`. I made the GitHub Release and incremented the version number/package documentation to the new development version. Once the package update manifests on CRAN I should be good to move forward on updating our team tutorial to use this function

**Comment by njlyon0** [comment]
## Posted on CRAN

We are live on CRAN! See [here](https://cran.r-project.org/web/packages/ltertools/index.html)

**Comment by njlyon0** [comment]
## Pull Request Opened!

I branched the team website repo (this repo), made the changes, and opened a new PR (see #13 ). I assigned Angel for review and hopefully it all looks good to her. Further details to come.

**Comment by njlyon0** [comment]
## Done

Angel confirmed this looked good to her and approved the PR so I merged it.

### Interesting Side Note

Turns out when I opened the PR, the way the GitHub Action was set up caused the dev branch's contents to be published on the living website. This feels not ideal (what if rendering doesn't work and thus undermines the purpose for doing this sort of dev work in a branch?) so I've tweaked the GHA `.yml` to--hopefully--only trigger on a commit to `main`. Note that this does include a **merged** PR but _NOT_ the **opening** of a PR.
