### ISSUE TITLE
[SciComp] Write new `scicomptools` function to export GitHub issues

### ISSUE THREAD

**Issue by angelchen7** [lter/scicomp#19]
## Summary

Thought it would be nice to write a function that, when given a url of a GitHub repo, will export GitHub issues from that repo. See #15 for context behind the idea.  

## Starting Tasks

- [x] Write function
- [x] Get feedback
- [x] Implement feedback
- [x] Update email in `scicomptools`
- [x] Increment version number to 1.1 in `NEWS.md` and `DESCRIPTION`
- [x] Edit `cran-comments.md`
- [x] submit it to CRAN again
- Once approved,
   - [x] create a GitHub release (`usethis::use_github_release`)
   - [x] update version number in `NEWS.md` and `DESCRIPTION` (`usethis::use_dev_version`)

## Useful links

- [scicomptools repo](https://github.com/NCEAS/scicomptools)

**Comment by njlyon0** [comment]
## `issue_extract` Feedback

Hey Angel! As requested, I took a look at the function and I love it! I have some minor suggestions but it's looking pretty solid to me.

- I'd add some error checks for some edge cases that are likely to occur
    - [ ] Missing GitHub URL
    - [ ] Malformed GitHub URL (might need to sort of regex this but essentially it just needs to have all the fundamental bits of the URL that your function relies on)
    - [ ] Either "start" or "end" is not a number
    - [ ] "export_folder" is either `NULL` or is length 0 (in that case maybe just warn the user and default to the value you define in the function?)
    - [ ] If "cookies" is provided but is not the right type of data file 
    - [ ] If "cooklies" is provided and is the right type of data file _but_ does not contain the right components (I can definitely see this bit going wrong in hard-to-diagnose ways without some error checks)
- [ ] Add a "quiet" argument that accepts a logical but defaults to `FALSE`
    - If it's `TRUE`, don't print the message for each exported issue
    - If it's not a logical, warn the user and coerce back to `FALSE` 
- [ ] Move the link explaining the cookies file to the parameter description for the "cookies" argument
    - Also, this feels like it isn't really 'optional' because it's required for non-public repos, right? Maybe adding a sentence about that would also be a good addition to the documentation for this argument
- [ ] I'd remove the example in lines 23-51 from the function and move it to the vignette
    - I think the ability to build in additional context that you get in vignette examples is maybe a better fit for a function use-case like this one
- [ ] Also--and I think this is mostly cosmetic--I think you could make the issue number padding a little more flexible
    - Maybe something like this:

```
  if(nchar(i) < nchar(end)){
    
    need_chars <- nchar(end) - nchar(i)
    
    num <- paste0(paste0(rep(x = "0", times = need_chars), collapse = ""), i)
    
  } else { num <- as.character(i) }
```

Broadly though the function looks great! Let me know if any of my feedback doesn't make sense and/or if you want to discuss further

**Comment by angelchen7** [comment]
## Incorporated feedback and submitted to CRAN

After I submitted to CRAN, I got back an email saying that the package did not pass their auto-checks:
```
Dear maintainer,

package scicomptools_1.1.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests (additional issue checks):
Windows: <https://win-builder.r-project.org/incoming_pretest/scicomptools_1.1.0_20241031_004501/Windows/00check.log>
Status: 2 NOTEs
Debian: <https://win-builder.r-project.org/incoming_pretest/scicomptools_1.1.0_20241031_004501/Debian/00check.log>
Status: 2 NOTEs

Last released version's CRAN status: OK: 13
See: <https://cran.r-project.org/web/checks/check_results_scicomptools.html>

CRAN Web: <https://cran.r-project.org/package=scicomptools>

Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/scicomptools_1.1.0_20241031_004501/>
The files will be removed after roughly 7 days.

No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
```

I already mentioned this note in my CRAN comments:
```
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NOTE
  Maintainer: 'Angel Chen <[angel777chen@gmail.com](mailto:angel777chen@gmail.com)>'

  New maintainer:
    Angel Chen <[angel777chen@gmail.com](mailto:angel777chen@gmail.com)>
  Old maintainer(s):
    Angel Chen <[anchen@nceas.ucsb.edu](mailto:anchen@nceas.ucsb.edu)>
```

However, I'm not sure how to debug this note:
```
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: DESCRIPTION meta-information, Result: NOTE
  Author field differs from that derived from Authors@R
    Author:    'Angel Chen [aut, cre] (<https://orcid.org/0000-0003-3515-6710>, [angelchen7.github.io](http://angelchen7.github.io/)), Nicholas J Lyon [aut] (<https://orcid.org/0000-0003-3905-1078>, [njlyon0.github.io](http://njlyon0.github.io/)), Gabriel Antunes Daldegan [aut] (<https://orcid.org/0000-0001-5345-4880>), Julien Brun [aut] (<https://orcid.org/0000-0002-7751-6238>), Gabe De La Rosa [ctb] ([www.gabrieldelarosa.com/](http://www.gabrieldelarosa.com/)), Kara Koenig [aut] (<https://orcid.org/0000-0002-6371-7821>), Kendall Miller [aut], Timothy D Nguyen [aut] ([www.linkedin.com/in/timothy-d-nguyen](http://www.linkedin.com/in/timothy-d-nguyen)), National Science Foundation [fnd] (NSF 1929393, 09/01/2019 - 08/31/2024), University of California, Santa Barbara [cph]'
    Authors@R: 'Angel Chen [aut, cre] (ORCID: <https://orcid.org/0000-0003-3515-6710>, Website: [angelchen7.github.io](http://angelchen7.github.io/)), Nicholas J Lyon [aut] (ORCID: <https://orcid.org/0000-0003-3905-1078>, Website: [njlyon0.github.io](http://njlyon0.github.io/)), Gabriel Antunes Daldegan [aut] (ORCID: <https://orcid.org/0000-0001-5345-4880>), Julien Brun [aut] (ORCID: <https://orcid.org/0000-0002-7751-6238>), Gabe De La Rosa [ctb] (Website: [www.gabrieldelarosa.com/](http://www.gabrieldelarosa.com/)), Kara Koenig [aut] (ORCID: <https://orcid.org/0000-0002-6371-7821>), Kendall Miller [aut], Timothy D Nguyen [aut] (Website: [www.linkedin.com/in/timothy-d-nguyen](http://www.linkedin.com/in/timothy-d-nguyen)), National Science Foundation [fnd] (NSF 1929393, 09/01/2019 - 08/31/2024), University of California, Santa Barbara [cph]'
```

To my understanding, `Author` is automatically generated from the `Authors@R` section in the DESCRIPTION so I don't know if this is a real issue or just a false positive...

**Comment by njlyon0** [comment]
Oh I just ran into this with another package! I think CRAN no longer supports providing more than one link per author (or at least paring down to one link / author was what silenced that NOTE for me.

See the `ltertools` [DESCRIPTION](https://github.com/lter/ltertools/blob/main/DESCRIPTION) file for the format that works and [this commit](https://github.com/lter/ltertools/commit/030d24fdce90c4bac044a0a3625355ab3a956e89) for the specific changes that fixed the NOTE

**Comment by angelchen7** [comment]
Thanks Nick!! I'll try that out and see if it works!

**Comment by angelchen7** [comment]
## Resubmitted to CRAN!

Now we wait...

**Comment by angelchen7** [comment]
## Approved by CRAN 🎉 

Finally CRAN approved it and I tagged the [GitHub release](https://github.com/NCEAS/scicomptools/releases/tag/v1.1.0) of scicomptools 1.1.0. Then I finished off by updating the version number to the development version in the NEWS and DESCRIPTION.
