### ISSUE TITLE
[SciComp] Finish up old tasks from GitHub Enterprise (Angel)

### ISSUE THREAD

**Issue by angelchen7** [lter/scicomp#3]
## Summary

Need to finish lingering tasks from GitHub Enterprise. See #1 

## Starting Tasks

- [x] See [#300](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/300) for the overview
   - [x]  Finish/migrate [#266](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues/266)

## Useful links

- [GitHub Enterprise Project for Angel](https://github.nceas.ucsb.edu/orgs/LTER/projects/9/views/1)

**Comment by njlyon0** [comment]
## Done

Migrated the JSON issue to #12 in this repo and updated with the latest of what we're thinking this task might look like
